Enable the iframe sandbox
GreenMeteor/spotify pull request #2
Opened 2022-04-07 14:44 UTC by dantefromhell

Enable the iframe sandbox to stronger isolate the embed iframe from the surrounding page and it's content. 
https://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/ is a basic explanation of the sandbox.

As HumHub allows to create private communities, which might touch on very sensitive or personal topics, embedded carry the risk of information leakage or tracking of users and content. Isolating the embed/ iframe as strongly as possible should be the standard measure to ensure this boundary.

Successfully tested on Brave (Chromium engine) and Firefox - both on Linux, wider testing with more Browsers should be considered.

2022-04-10 15:59 UTC, ArchBlood commented
Hello, thank you for the detailed p/r, although I am sorry to say that we can not accept this p/r due to the restrictions made.

- Sharing to other platforms creates pop-up windows which call `window.open()` in most cases, using this p/r prevents this which can be seen as a broken function which is also not good for the platform using the module or the third-party creator.
- We recommend using '[sandbox](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox)' within your CSP configurations if **_needed_**, this does not mean it should be used just a suggestion.

I would also like to note the following should be known before using `sandbox=""` attribute
> You can find a full list of pre-defined values for `sandbox=""` in the following link;
https://www.w3schools.com/tags/att_iframe_sandbox.asp

- treat the content as being from a unique origin
- block form submission
- block script execution
- disable APIs
- prevent links from targeting other browsing contexts
- prevent content from using plugins (through <embed>, <object>, <applet>, or other)
- prevent the content to navigate its top-level browsing context
- block automatically triggered features (such as automatically playing a video or automatically focusing a form control)

2022-04-13 18:24 UTC, dantefromhell commented
> Sharing to other platforms creates pop-up windows which call window.open() in most cases, using this p/r prevents this which can be seen as a broken function which is also not good for the platform using the module or the third-party creator.

This would be the `allow-popups` permission that can be added to the sandbox without problem.

> We recommend using '[sandbox](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox)' within your CSP configurations if needed, this does not mean it should be used just a suggestion.

This is exactly what the linked article talks about. CSP are binary in nature what pages are allowed to include, but not what they are allowed to do. The intention of this PR is to protect private communities from being spied upon by BigTech companies through their embedded integrations. This type of protection can not be done by CSPs at all.

2022-04-15 01:42 UTC, ArchBlood commented
> > Sharing to other platforms creates pop-up windows which call window.open() in most cases, using this p/r prevents this which can be seen as a broken function which is also not good for the platform using the module or the third-party creator.
> 
> This would be the `allow-popups` permission that can be added to the sandbox without problem.
> 
> > We recommend using '[sandbox](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox)' within your CSP configurations if needed, this does not mean it should be used just a suggestion.
> 
> This is exactly what the linked article talks about. CSP are binary in nature what pages are allowed to include, but not what they are allowed to do. The intention of this PR is to protect private communities from being spied upon by BigTech companies through their embedded integrations. This type of protection can not be done by CSPs at all.

This is still more used for personal use and not something we're looking into adding into the core of the module, we could however create a separate branch release if need be for users with completely private networks, this, however, will not be uploaded to the marketplace and the users will have to download it manually for updates.

2022-04-15 01:46 UTC, ArchBlood requested changes
Please update the changelogs to reflect the changes, thanks

https://github.com/GreenMeteor/spotify/blob/private-communities/docs/CHANGELOG.md

2022-05-15 04:05 UTC, ArchBlood approved these changes

2022-05-15 04:05 UTC, merged

2022-05-16 10:27 UTC, dantefromhell commented
Apologies for dropping the ball here and thanks for completing the PR - highly appreciated 👍🏽 

I'm not sure I understand the argument for private community though. What exactly do you mean by "private use"? And why/ how does that differ from other uses?

2022-05-16 13:35 UTC, ArchBlood commented
> Apologies for dropping the ball here and thanks for completing the PR - highly appreciated 👍🏽 
> 
> I'm not sure I understand the argument for private community though. What exactly do you mean by "private use"? And why/ how does that differ from other uses?

It's more for personal preference what you may want others may not.

2022-05-17 11:14 UTC, dantefromhell commented
@ArchBlood This is not about personal preferences for me, but security best practices. Embedding third-party (aka untrusted) content in any site creates an attack vector and that increases risk. The risk is higher for private communities but not 0 for public or open-signup communities either.

See [1] for the "official" reference to the web security best practices around iframes.

[1] https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html#sandboxed-frames

2022-05-17 23:22 UTC, ArchBlood commented
> @ArchBlood This is not about personal preferences for me, but security best practices. Embedding third-party (aka untrusted) content in any site creates an attack vector and that increases risk. The risk is higher for private communities but not 0 for public or open-signup communities either.
> 
> See [1] for the "official" reference to the web security best practices around iframes.
> 
> [1] https://cheatsheetseries.owasp.org/cheatsheets/HTML5_Security_Cheat_Sheet.html#sandboxed-frames

Could you provide information where Spotify should be restricted in such a way though? I'm still not seeing any issues that warrants this being added to the core of the module.

It comes down to, do you yourself trust Spotify or do you not? This is why the second branch was created for this.

I can see your points about wanting to make your site(s) as safe as possible, but as it stands I do not see any issues where Spotify is affecting any components of a HumHub sites. 🤔

If you do find anything currently being affected please do open an issue and we can discuss this more and maybe then also try to discuss with the Spotify team as well about your concerns with how the embeds are handled.